# Generated by Django 2.0.1 on 2018-01-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20180116_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='client',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supplier',
            field=models.ManyToManyField(null=True, to='controller.Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
